name: Build and Deploy
permissions:
  contents: write
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.13.2'

      - name: Deploy 
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: newversion #The branch the action should deploy to.
          folder: .
